# Generated by Django 6.1 on 2026-09-02 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(help_text='Who gave this income', max_length=150)),
                ('income_type', models.CharField(choices=[('ZAKAT', 'Zakat'), ('SADQA', 'Sadqa'), ('SADQA_E_FITAR', 'Sadqa-e-Fitar'), ('USHAR', 'Ushar'), ('FEE', 'Fee'), ('DONATION', 'General Donation'), ('OTHER', 'Other')], default='DONATION', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
