# Generated by Django 6.1 on 2026-09-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+92 300 1234567', max_length=50)),
                ('email', models.EmailField(default='info@roshanhunarmarkaz.edu.pk', max_length=254)),
                ('address', models.CharField(default='Main Campus Road, Islamabad, Pakistan', max_length=255)),
                ('facebook_url', models.URLField(blank=True, help_text="Full URL to the school's Facebook page")),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_title', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
